// Rótulos amigáveis exibidos em /conteudo. Chaves não listadas aqui aparecem
// com o próprio nome do campo.
export const labels: Record<string, string> = {
  // comuns
  seo: "Google / título da aba (SEO)",
  title: "Título",
  description: "Descrição",
  eyebrow: "Texto pequeno acima do título",
  titleLine1: "Título — linha 1",
  titleLine2: "Título — linha 2 (destacada)",
  titleLine2Highlight: "Título — linha 2 (destacada em verde)",
  text: "Texto",
  button: "Botão",
  cta: "Chamada final",
  items: "Itens",
  label: "Rótulo",
  // home
  hero: "Topo da página",
  lead: "Texto de apoio",
  primaryButton: "Botão principal",
  secondaryButton: "Botão secundário",
  solutions: "Seção Soluções",
  cards: "Cartões (tópicos em cada um)",
  linkLabel: "Texto do link",
  linkHref: "Endereço do link",
  method: "Seção Método",
  steps: "Etapas",
  detailTitle: "Título ampliado",
  summary: "Resumo",
  explanation: "Explicação",
  points: "Pontos-chave",
  // engenharia
  services: "Cartões de serviços",
  process: "Seção Processo",
  applications: "Contextos de aplicação",
  tags: "Etiquetas",
  // global
  nav: "Menu",
  skipLink: "Link \"Pular para o conteúdo\" (leitores de tela)",
  home: "Home",
  engineering: "Engenharia",
  systems: "Sistemas",
  about: "Sobre nós",
  contact: "Contato",
  footer: "Rodapé",
  line1: "Linha 1",
  line2: "Linha 2",
  copyrightName: "Nome no copyright",
  legalNotice: "Link de avisos legais",
  privacyPolicy: "Link de privacidade",
  pageChrome: "Textos fixos das páginas internas",
  heroRightLabel: "Rótulo à direita do topo",
  heroFooterLabel: "Rótulo no rodapé do topo",
  ctaEyebrow: "Texto pequeno da chamada final",
  heroPanels: "Balões dos ícones do topo",
  chat: "Assistente (chat)",
  kicker: "Texto pequeno",
  inactiveNotice: "Aviso com o chat inativo",
  shortcuts: "Atalhos",
  userLabel: "Rótulo do usuário",
  assistantLabel: "Rótulo do assistente",
  inputLabel: "Rótulo do campo",
  placeholderActive: "Placeholder (ativo)",
  placeholderInactive: "Placeholder (inativo)",
  sendButton: "Botão enviar",
  waitingButton: "Botão aguardando",
  errorMessage: "Mensagem de erro",
  // contato
  form: "Formulário",
  channelNotice: "Aviso de canal em configuração",
  nameLabel: "Campo nome — rótulo",
  namePlaceholder: "Campo nome — placeholder",
  phoneLabel: "Campo WhatsApp — rótulo",
  phonePlaceholder: "Campo WhatsApp — placeholder",
  needLabel: "Tipo de necessidade — rótulo",
  needPlaceholder: "Tipo de necessidade — opção vazia",
  needs: "Opções de tipo de necessidade",
  defaultForEngineering: "Opção pré-selecionada vindo de Engenharia",
  defaultForSystems: "Opção pré-selecionada vindo de Sistemas",
  defaultForBoth: "Opção pré-selecionada vindo de ambos",
  messageLabel: "Campo mensagem — rótulo",
  messagePlaceholder: "Campo mensagem — placeholder",
  submitButton: "Botão de envio",
  privacyText: "Texto de privacidade",
  privacyLink: "Link de privacidade",
  noscript: "Aviso sem JavaScript",
  errors: "Mensagens de erro do formulário",
  name: "Nome",
  phone: "Telefone",
  need: "Necessidade",
  message: "Mensagem",
  feedbackReview: "Aviso: revisar campos",
  feedbackNoChannel: "Aviso: WhatsApp indisponível",
  feedbackPrepared: "Aviso: mensagem preparada",
  whatsappLink: "Link para abrir o WhatsApp",
  previewSummary: "Título da prévia da mensagem",
  whatsappMessage: "Mensagem que segue para o WhatsApp",
  greeting: "Saudação",
  loadingForm: "Texto enquanto o formulário carrega",
  // sistemas
  showcase: "Vitrine de sistemas",
  examples: "Exemplos",
  dashboard: "Exemplo: Dashboard",
  finance: "Exemplo: Financeiro",
  projects: "Exemplo: Projetos",
  authorial: "Projetos autorais",
  kickerPrefix: "Prefixo do texto pequeno",
  cases: "Sistemas (3 fixos)",
  type: "Tipo",
  objective: "Objetivo",
  focus: "Abordagem",
  // sobre
  timeline: "Timeline",
  rangeLabel: "Período (rótulo)",
  milestones: "Marcos (6 fixos)",
  date: "Data",
  brand: "Marca (opcional)",
  author: "Assinatura final",
  textLine1: "Texto — linha 1",
  textLine2: "Texto — linha 2",
  // projetos
  section: "Cabeçalho da seção de projetos",
  placeholder: "Aviso quando não há projetos",
  paragraph1: "Parágrafo 1",
  paragraph2: "Parágrafo 2",
  cardLabels: "Rótulos dos cartões de projeto",
  challenge: "Desafio",
  scope: "Escopo",
  contribution: "Atuação",
  result: "Resultado",
  learnMore: "Prefixo do link",
  slug: "Identificador (não alterar)",
  published: "Publicado no site",
  category: "Categoria (Engenharia, Sistemas ou Consultoria)",
  sector: "Setor",
  status: "Status",
  client: "Cliente (opcional)",
  city: "Local (opcional)",
  problem: "Desafio",
  verifiedResult: "Resultado verificado (opcional)",
  disciplines: "Disciplinas",
  href: "Link (opcional)",
  images: "Fotos",
  src: "Arquivo da foto",
  alt: "Descrição da foto (acessibilidade)",
  width: "Largura (px)",
  height: "Altura (px)",
  // legais
  sections: "Blocos de texto",
  anchor: "Âncora (opcional, ex: privacidade)",
  paragraphs: "Parágrafos (aceita [texto](link))",
  references: "Referências (aceita [texto](link))",
};

// Listas cujo tamanho o layout não suporta variar (só edição e reordenação).
export const fixedLists = new Set(["milestones", "cases"]);

// Campos longos usam área de texto em vez de linha única.
export const longFields = new Set([
  "lead",
  "text",
  "explanation",
  "description",
  "paragraphs",
  "references",
]);
